default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
development:
  <<: *default
  database: newmanyoutask_development
test:
  <<: *default
  database: newmanyoutask_test
production:
  <<: *default
  database: newmanyoutask_production
  username: newmanyoutask
  password: <%= ENV['newmanyoutask_DATABASE_PASSWORD'] %>
